name: Full Recon & Vulnerability Assessment

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain for Full Recon'
        required: true
        default: 'raneen.com'

jobs:
  Recon:
    runs-on: ubuntu-latest
    container: booyaabes/kali-linux-full
    env:
      DOMAIN: ${{ github.event.inputs.domain }}
    steps:
      - name: Run a command inside Kali container
        run: |
          echo "Running inside Kali container"
          nmap --version
          nmap -T4 -A -v -p- $DOMAIN 
