name: Full Recon & Vulnerability Assessment

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain for Full Recon'
        required: true
        default: 'raneen.com'

jobs:
  Recon:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOMAIN: ${{ github.event.inputs.domain }}
    steps:
      - name: Install tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends nmap python3-pip
          pip3 install wfuzz
      - name: Run nmap
        run: |
          nmap --version
          mkdir -p results
          nmap -T4 -p- --min-rate 1000 --max-retries 1 -A -v $DOMAIN -oA results/$DOMAIN || true
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: nmap-results-$DOMAIN
          path: results
